name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Create Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ef8d97285399b9ccfd8acf9e0796cd16
          filename: fsm-sdk-badge.json
          label: Hello
          message: World
          color: orange


